### ISSUE TITLE
Status code is not available from Behat\Mink\Driver\Selenium2Driver

### ISSUE THREAD

**Issue by iby** [minkphp/MinkSelenium2Driver#165]
When running Selenium / PhantomJS. When running Selenium I can see a window opening and everything working. When using Goutte everything works fine. Am I missing something obvious?

```
default:
    extensions:
        Behat\MinkExtension:
            base_url: 'http://my.pimtellect.tst/'
            sessions:
                default:
                    selenium2:
                        browser: chrome

    suites:
        default:
        # …
```
