### ISSUE TITLE
Chrome capabilities no longer supports switches syntax

### ISSUE THREAD

**Issue by iby** [minkphp/MinkSelenium2Driver#174]
Newer versions of the driver do not support the switches syntax – specifying it in `behat.yml` will not cause an exception but the config will equally not have any effect. I didn't find the original source, but [here](https://github.com/admc/wd/issues/147#issuecomment-21191552) and [here](http://wiki.chromedriver.googlecode.com/git-history/2e0ac3c1f19443f1dd4bb078129f8fb9602768da/CapabilitiesAndSwitches.wiki) are the references of the change: 

> Note, ChromeDriver no longer supports old-style capabilities. Old-style capabilities include any chrome.`*` capability (e.g., chrome.switches). You should use the ChromeOptions class for you language.

Per example in [this](https://github.com/Behat/MinkSelenium2Driver/issues/3) ticket, this:

``` yml
selenium2:
    browser: chrome
    capabilities:
        # browserName: firefox
        # version: 8
        # platform: ANY
        # browserVersion: 8
        # browser: firefox
        chrome.binary: "/path/to/chrome"
        chrome.nativeEvents: true
        chrome.switches:
            - "--start-maximized"
            - "--disable-translate"
            # - "--proxy-server=http://localhost:3128"
            # - "--another=one"
```

Becomes this:

``` yml
selenium2:
    browser: chrome
    capabilities:
        # browserName: firefox
        # version: 8
        # platform: ANY
        # browserVersion: 8
        # browser: firefox
        chrome.binary: "/path/to/chrome"
        chrome.nativeEvents: true
        extra_capabilities:
            chromeOptions:
                args:
                    - "--start-maximized"
                    - "--disable-translate"
                    # - "--proxy-server=http://localhost:3128"
                    # - "--another=one"
```

It would make sense to automatically replicate this configuration to support the new drivers and keep the compatibility for the older ones. Also `Selenium2Factory` supports the following syntax for `chrome`:

``` php
->arrayNode('chrome')
    ->children()
        ->arrayNode('switches')->prototype('scalar')->end()->end()
        ->scalarNode('binary')->end()
        ->arrayNode('extensions')->prototype('scalar')->end()->end()
    ->end()
->end()
```

It would be good to have the 'chromeOptions' sibling with all of the allowed options.
