### ISSUE TITLE
Accessor for desiredCapabilities

### ISSUE THREAD

**Issue by cmacnaughton-al** [minkphp/MinkSelenium2Driver#202]
Is there a reason there's no accessor for desiredCapabilities? (ie. getDesiredCapabilities())?

Thanks!

**Comment by aik099** [comment]
I guess because getting desired capabilities after driver creation isn't of any use.

If you have any specific use case, then please share.

**Comment by cmacnaughton-al** [comment]
The use case I'm looking at is when using Sauce Labs for Behat testing.  I have multiple profiles set up in my behat.yml file for different browsers that look like this:
```
Firefox:
  extensions:
    Behat\MinkExtension:
      selenium2:
        browser: chrome
        wd_host: myname:myApiKeyxxxxxxx@ondemand.saucelabs.com/wd/hub
        capabilities: {"platform":"Windows 8.1","browserName":"chrome","version":"35"}
```
I have a requirement to access the data in the "capabilities" field inside of my featureContext.php file during some Behat test steps for logging/reporting purposes and to call services that may require that data, specifically the browser version.  In any case, the only place I can find that data (as well as other fields like deviceType, and deviceOrientation) is in the private desiredCapbilities field in the Selenium2Driver returned by calling
 ```
$this->getSession()->getDriver()
```
from inside a method in featureContext.php.

An accessor for this would accomplish what I'm after, however I'm no expert on any of this, so if there's a more appropriate way of accessing this information please let me know.
