### ISSUE TITLE
Documentation for configuration options in behat.yml

### ISSUE THREAD

**Issue by zuernBernhard** [minkphp/MinkSelenium2Driver#272]
Hi togehter, 
I'm using MinkSelenium2Driver together with Mink and Behat. 

The Configuration of behat via behat.yml is documented on [http://behat.org/en/v2.5/guides/7.config.html](http://behat.org/en/v2.5/guides/7.config.html). 

The configuration for the Behat-Mink-Extension via behat.yml is documented on: [https://github.com/Behat/MinkExtension/blob/master/doc/index.rst](https://github.com/Behat/MinkExtension/blob/master/doc/index.rst)

But there can one see how Selenum2 can be configured via behat.yml in the directive ?

```
default:
  extensions:
    Behat\MinkExtension:
      sessions:
              default:
                selenium2: ~
```

Can this be documented in the README.md of this project or is it possible to link this part of documentation in the README.md of this project ? So that it is possible to find out how to set for example the **wd_host** option for Selenium2 from behat.yml
