### ISSUE TITLE
missing capabilites options

### ISSUE THREAD

**Issue by brikou** [minkphp/MinkSelenium2Driver#3]
When using Chrome with this driver, it should be possible to set some more capabilites (specific to chrome browser)...

Here is what my `behat.yml` should look like

``` yaml
default:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: http://en.wikipedia.org
            goutte: ~
            selenium2:
                browser: chrome
                capabilities:
                    # browserName: firefox
                    # version: 8
                    # platform: ANY
                    # browserVersion: 8
                    # browser: firefox
                    chrome.binary: "/path/to/chrome"
                    chrome.nativeEvents: true
                    chrome.switches:
                        - "--start-maximized"
                        - "--disable-translate"
                        # - "--proxy-server=http://localhost:3128"
                        # - "--another=one"

```

Too bad this configuration is not allowed (yet)

Cheer
